# SPDX-FileCopyrightText: 2024 Chen Linxuan <me@black-desk.cn>
# SPDX-License-Identifier: GPL-3.0-or-later

version: 2
updates:
  # Keep Python dependencies up-to-date
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 10
    versioning-strategy: "lockfile-only"
    labels:
      - "dependencies"
    allow:
      # Allow all dependency updates, but prioritize security updates
      - dependency-type: "all"
    commit-message:
      prefix: "deps"

  # Keep GitHub Actions up-to-date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"